[workspace]
members = ["day_1", "day_2", "day_3", "day_4", "day_4_nom", "day_5"]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
aoc-cache = "0.2"
nom = "7"
rayon = "1.6"
