[package]
name = "day_4_nom"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc-cache = { workspace = true }
nom = { workspace = true }
